<div class="container" style="margin-top: 70px">
<?php if(isset($error)): ?>
	<div class="panel panel-danger">
		<div class="panel-heading">
			<h3 class="panel-title">Thông báo</h3>
		</div>
		<div class="panel-body">
			<?=$error ?>
		</div>
	</div>
<?php 
	else:
		if(!isset($detail)):

			$title = '10Quiz Kết quả tìm kiếm ';

			if(!empty($query['keywords']))
				$title.= $query['keywords'];

			echo $this->headMeta()
			     ->setProperty('og:title', $title);

			echo $this->headTitle('Kết quả tìm kiếm');
?>
	<div class="panel panel-primary">
		<div class="panel-heading">
			<h5 class="panel-title">Kết quả tìm kiếm <?= $tests->count() > 0 ? 'có <strong>'.$tests->count().' đề thi</strong>' : ''?></h5>
		</div>
		<div class="panel-body">
			<div class="row">
			<?php
				if($tests->count() == 0):
					echo "<div class='col-sm-12'>Không có đề thi nào</div>";
				else:
					if(isset($author) && in_array($author->role_id, [1, 3]))
					{
						$panel = <<< EOD
							<div class="col-sm-12">
							<div class="panel panel-default">
								<div class="panel-body text-uppercase text-center">
									<strong>Danh sách đề thi của $author->fullname</strong>
								</div>
							</div></div>
EOD;
						echo $panel;
					}

					$i = 1 + ($page - 1)*10;
					foreach($tests as $test):
						$id = $test->test_id;
						$date = date_format(date_create($test->created_date), 'd/m/Y');
						if(!empty($test->img))
						$img = $this->basePath('img/tests/'.$test->img);
					else
						$img = $this->basePath('img/10quiz.png');
			?>
				<div class="col-md-3 col-sm-4 col-xs-12">
					<div class="panel panel-default panel-test">
						<div class="img-test">
							<img src="<?= $img ?>" alt="img-<?= $test->test_name?>"/>
						</div>
						<div class="panel-body">
							<h4><?= $test->test_name?></h4>
							<div>
								<span class="label label-primary">
									<i class="fa fa-user" aria-hidden="true"></i> <a href="<?= $this->url('test/public', [], ['query' => [ 'author_id' => $test->user_id ]])?>"><?= $test->fullname ?></a>
								</span>
								<span class="label label-success">
									<i class="fa fa-question-circle-o" aria-hidden="true"></i> <?= $test->question_count ?> câu
								</span>
								<span class="label label-danger">
									<i class="fa fa-clock-o" aria-hidden="true"></i> <?= $test->time_limit ?> phút
								</span>
								<span class="label label-info"><i class="fa fa-line-chart" aria-hidden="true"></i> <?= $test->result_count?> lượt làm</span>
								<?php if($test->is_login): ?>
									<span class="label label-default">
										<i class="fa fa-key" aria-hidden="true"></i> 
									</span>
								<?php endif;?>
							</div>
						</div>
						<div class="panel-footer" style="background: white">
							<a class="btn btn-sm btn-primary" href="<?= $this->url('test/start', ['id' => $test->test_id])?>"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> Làm bài</a>
							<?php 

								if(!empty($user)):
									if($user->user_id == $test->user_id || $user->role_id == 3)
										echo '<a class="btn btn-sm btn-success" href="'.$this->url('test/edit', ['id' => $test->test_id]).'"><i class="fa fa-pencil" aria-hidden="true"></i> Sửa</a>';
							?>
								<a class="btn btn-sm btn-default" href="<?= $this->url('test/public', [], ['query' => [ 'detail' => $test->test_id ]])?>"><i class="fa fa-eye" aria-hidden="true"></i> Xem</a>
							<?php endif; ?>
						</div>
					</div>
				</div>
			<?php $i++; endforeach; ?>
			</div>
			<div class="row">
				<?= $this->paginationControl($tests, 'sliding', 'partial/paginator', ['route' => 'test/public', 'query' => $query]) ?>
			</div>

			<?php endif;?>
		</div>
	</div>
	<?php else: ?>
		<?= $this->inlineScript()->setFile($this->basePath('js/jQuery.tagify.min.js'))?>
		<div class="panel panel-default panel-border-top">
			<div class="panel-body">
				<h4 class="text-center">CHI TIẾT ĐỀ THI <?= mb_strtoupper($test['test_name'], 'utf8') ?></h4>
			</div>
		</div>
		
		<div class="panel panel-primary">
			<div class="panel-heading">
				<h3 class="panel-title">Danh sách câu hỏi</h3>
			</div>
			<div class="panel-body">
				<?php
					$i = 1;
					foreach ($questions as $q):
				?>
					<input type="checkbox" value="<?= $q->question_id?>"/> Chọn để thêm vào bộ câu hỏi
					<h4>Câu <?= $i?></h4>
					<div class="panel panel-question-text">
						<div class="panel-body">
							<?= $q->question_text; ?>
						</div>
					</div>

					<div>Loại câu: <label class="label label-primary">
						<?php 
							switch(intval($q->question_type_id))
							{
								case 1:
									echo 'Một lựa chọn';
									break;
								case 2:
									echo 'Nhiều lựa chọn';
									break;
								case 3:
									echo 'Sắp xếp';
									break;
								case 4:
									echo 'Ghép cột';
									break;
								case 5:
									echo 'Phân loại';
									break;
								case 6:
									echo 'Trả lời ngắn';
									break;
								case 7:
									echo 'Đoạn văn';
									break;
								case 8:
									echo 'Điền từ';
									break;
								case 9:
									echo 'File';
									break;
							}
						?>
					</label></div>

					<hr/>

					<h4 class="text-primary">Đáp án</h4>

					<table class="table table-option" id="table-option-<?= $q->question_id ?>" style="margin-bottom: 10px;">
						<tbody>
							<?php
								switch(intval($q->question_type_id))
								{
									case 1:
									case 2:
										foreach ($q->question_options as $option) {

											if($option->is_correct)
												echo <<<EOD
													<tr>
														<td class="index"><i class='fa fa-check text-success' aria-hidden='true'></i> {$option->index}. </td>
														<td>$option->option_text</td>
													</tr>
EOD;
											else
												echo <<<EOD
													<tr>
														<td class="index"><span style='padding-left: 20px'> $option->index. </span></td>
														<td>$option->option_text</td>
													</tr>
EOD;

										}
										break;
									case 3:
										foreach ($q->question_options as $option) {
												echo <<<EOD
													<tr>
														<td class="index"><i class="fa fa-sort fa-2x" aria-hidden="true"></td>
														<td>$option->option_text</td>
													</tr>
EOD;
										}

										echo <<<EOD
										<script>
											$().ready(function(){
												$('#table-option-{$q->question_id} tbody').sortable({disabled: true});
											});
										</script>
EOD;
										break;
									case 4:
										foreach ($q->question_options as $option) {
												echo <<<EOD
													<tr class="row">
														<td class="col-sm-5"><div class="source">{$option->source->data}</div></td>
														<td class="col-sm-1 text-center"><i class="fa fa-long-arrow-right fa-2x"></i></td>
														<td class="col-sm-5"><div class="target">{$option->target->data}</div></td>
													</tr>
EOD;
										}
										break;
									case 5:
										foreach ($q->question_options as $option) {
												echo <<<EOD
													<tr class="row">
														<td class="col-sm-1"><h3 style="margin:0"><span class="label label-primary">{$option->group_text}</span></h3></td>
														<td><input class="group_items" value="{$option->group_items}"></td>
													</tr>
EOD;
										}

										echo<<<EOD
											<script>
												$().ready(function(){
													$('#table-option-{$q->question_id} tbody').find('.group_items').tagify({delimiters: ';'});
													$('#table-option-{$q->question_id} tbody').find('.tagify .tagify__input').attr('contenteditable', 'false');
													$('#table-option-{$q->question_id} tbody').find('.tagify x').remove();
												});
											</script>
EOD;
										break;
									case 6:
										foreach ($q->question_options as $option) {
												echo <<<EOD
													<tr>
														<td class="index">-</td>
														<td class="option-text">{$option->option_text}</td>
													</tr>
EOD;

										}
										break;
									case 8:
										foreach ($q->question_options as $option) {
												$fill_words = json_encode($option->fill_words);
												echo <<<EOD
													<tr>
														<td class="index"><span style='padding-left: 20px'> {$option->index}. </span></td>
														<td class="option-text">{$option->option_text}</td>
													</tr>
													<script>
														$().ready(function(){

															var fill_words = $fill_words;			

															$('#table-option-{$q->question_id} tbody').find('tr .option-text').each(function(index, value){

																$(value).find('input').each(function(index_input, input){

																	$(input).val(fill_words[index_input]);
																	$(input).prop('disabled', 'disabled');

																});

															});

														});
													</script>
EOD;

										}
										break;
									case 7:
									case 9:
										break;
								}

							?>
						</tbody>
					</table>
					<hr/>

				<?php $i++; endforeach; ?>
			</div>
			<div class="panel-footer">
				<button type="button" class="btn btn-primary" id="btnAdd">Thêm vào bộ câu hỏi</button>
			</div>
		</div>
		<script>
			$().ready(function(e){

				var list = [];
				var urlQuestion = "<?= $this->url('question') ?>";

				$('#btnAdd').click(function(e){

					$.each($('input:checkbox'), function(i, e){

						if($(e).prop('checked'))
						{
							list.push($(e).val());
						}

					});

					if(list.length == 0)
					{
						$.notify('Bạn chưa chọn câu hỏi', {type: 'info'});
						return;
					}

					$.ajax({
						url: urlQuestion + '/insert',
						data:JSON.stringify({list: list}),
						dataType: 'json',
						method: 'post',
						success: function(res){
							if(res.ok == 1)
							{
								$.notify('Đã thêm thành công ' + list.length + ' vào bộ câu hỏi', { type: 'success' });
							}
							else
							{
								$.notify(res.msg, { type: 'danger' });
							}
						}
					});

				});
			});
		</script>
	<?php endif; ?>
<?php endif; ?>
</div>