<?= $this->headTitle('Xác thực tài khoản') ?>
<div class="container">
    <div class="col-sm-4 col-sm-offset-4" style="top: 150px; position: relative">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Xác thực tài khoản</h3>
            </div>
            <div class="panel-body">
                <?= $msg ?>
            </div>
            <div class="panel-footer">
				<a href="<?= $this->url('login') ?>" class="btn btn-default">Đăng nhập</a>
			</div>
        </div>
    </div>
</div>