<?= $this->headTitle('Chỉnh sửa thông tin tài khoản')?>
<?= $this->partial('user/user/editinfo', ['form' => $form, 'pageAdmin' => true]) ?>
<?php
	if(isset($data_active)):
?>
<div class="container">
	<div class="col-sm-6 col-sm-offset-3">
		<div class="panel panel-primary">
			<div class="panel-heading">
				<div class="panel-title">Phê duyệt tài khoản người ra đề</div>
			</div>
			<div class="panel-body">
				<form method="POST" role="form">
					<?= $this->formHidden($form->get('user_id')) ?>
					<div class="radio">
						<label>
							<input type="radio" name="state" value="1" <?= $data_active['state'] == 1 ? 'checked="checked"' : ''?>> Cho phép
						</label>
					</div>
					<div class="radio">
						<label>
							<input type="radio" name="state" value="0" <?= $data_active['state'] == 0 ? 'checked="checked"' : ''?> /> Không cho phép
						</label>
					</div>
					<div class="form-group">
						<button type="submit" name="btnActive" class="btn btn-primary">OK</button>
					</div>
				</form>
			</div>
		</div>
	</div>
</div>

<?php endif; ?>

<?php if(!isset($isAdmin)): ?>

<div class="container">
	<div class="col-sm-6 col-sm-offset-3">
		<div class="panel panel-danger">
			<div class="panel-heading">
				<h3 class="panel-title">Xoá tài khoản</h3>
			</div>
			<div class="panel-body">
				<button type="button" class="btn btn-danger" data-toggle="modal" data-target="#modal">Xoá</button>
				<form method="post" name="frmDelete">
					<?= $this->formHidden($form->get('user_id'))?>
					<input type="hidden" name="btnDelete" />
				</form>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modal">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Xoá tài khoản</h4>
			</div>
			<div class="modal-body">
				Lưu ý: Các dữ liệu về tài khoản sẽ bị xoá.
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
				<button type="button" class="btn btn-danger btnDelete">Đồng ý</button>
			</div>
		</div>
	</div>
</div>

<?php endif; ?>

<script type="text/javascript">

	$().ready(function(){
		$('#modal .btnDelete').click(function(){

			$('form[name=frmDelete]').submit();

		});
	});

</script>
