<?php

$this->headMeta()
	->setProperty('og:title', '10Quiz Đăng nhập')
	->setProperty('og:url', $this->url('login', [], [ 'force_canonical' => true ]));

echo $this->headMeta();
echo $this->headTitle('Đăng nhập');

$login = $formLogin->get('login');
$login->setAttribute('class', 'btn btn-primary');
$login->setAttribute('value', 'Đăng nhập');

$username = $formLogin->get('username');
$username->setAttribute('class', 'form-control');
$username->setAttribute('required', 'required');
$username->setAttribute('placeholder', 'Nhập tên tài khoản');

$password = $formLogin->get('password');
$password->setAttribute('class', 'form-control');
$password->setAttribute('required', 'required');
$password->setAttribute('placeholder', 'Nhập mật khẩu');

$remember = $formLogin->get('remember');

$formLogin->prepare();
echo $this->form()->openTag($formLogin);

?>

<div class="container">
    <div class="col-md-4 col-md-offset-4 col-sm-6 col-sm-offset-3 col-xs-12">
        <div class="panel panel-primary">
            <div class="panel-heading">
                <h3 class="panel-title">Đăng nhập</h3>
            </div>
            <div class="panel-body">

				<?php if(isset($error_message)): ?>
				<div class="alert alert-danger" style="margin-top: 10px">
					<button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
					<strong>Lỗi! </strong> <?= $error_message ?>
				</div>
				<?php endif; ?>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-addon"><i class="fa fa-user" aria-hidden="true" style="width: 13px"></i>
				</div>
						<?= $this->formElement($username)?>
					</div>
				</div>

				<div class="form-group">
					<div class="input-group">
						<div class="input-group-addon"><i class="fa fa-key" aria-hidden="true"></i>
				</div>
						<?= $this->formElement($password)?>
					</div>
				</div>

				<div class="form-group">
					<div class="checkbox">
						<label>
							<?= $this->formElement($remember) ?>
							<?= $this->formLabel($remember) ?>
						</label>
					</div>
				</div>

				<div class="row">
					<div class="col-sm-6">
						<a href="<?= $this->url('forgot')?>" class="btn btn-default btn-block">Quên mật khẩu?</a>
					</div>
					<div class="col-sm-6">
						<button type="submit" name="login" class="btn btn-primary btn-block">Đăng nhập</button>
					</div>
				</div>

				<div class="row">
					<div class="col-sm-12">
						<div style="margin-top: 10px">TK: giaovien1-giaovien1</div>
					</div>
				</div>

				<?= $this->form()->closeTag($formLogin)?>

			</div>
        </div>
    </div>
</div>