<div class="container">

<?php

	echo $this->headMeta()
	->setProperty('og:title', '10Quiz Quản lí danh mục');

	echo $this->headTitle('Quản lí danh mục');

?>

<?php if(isset($error)): ?>

<div class="panel panel-danger">
	<div class="panel-heading">
		<h3 class="panel-title">Thông báo</h3>
	</div>
	<div class="panel-body">
		<?= $error ?>
	</div>
</div>

<?php else: ?>

<?= $this->inlineScript()->setFile($this->basePath('js/mustache.min.js'))?>

<?=  $this->headTitle('Quản lý danh mục')?>

<?php
	if(isset($admin))
	{
		$sel = "<select name='user' class='form-control'>";
		$sel .="<option value='' selected>Chọn tài khoản</option>";

		foreach ($users as $item) {
			$sel .="<option value='{$item['user_id']}'>{$item['username']}</option>";
		}
		
		$sel .="</select>";
		echo '<script>var admin = true; var users = "'.$sel.'";</script>';
	}

?>

<div class="panel panel-primary">
	<div class="panel-heading panel-button">
		<button type="button" class="btn btn-default btn-sm pull-right" id="btnAdd"><i class="fa fa-plus" aria-hidden="true"></i> Thêm loại mới</button>
		<h5 class="panel-title">Danh mục câu hỏi</h5>
	</div>
	<div class="panel-body">
		<div class="table-responsive">
			<table class="table table-hover v-align-middle table-bordered" id="table_category">
				<thead>
					<tr>
						<th>STT</th><th>Tên danh mục</th><th>Số lượng câu hỏi</th><?= isset($admin) ? '<th>Người tạo</th>' : ''?><th>Thao tác</th>
					</tr>
				</thead>
				<tbody>
					<tr>
						<td></td>
					</tr>
				</tbody>
			</table>
		</div>
	</div>
</div>

<div class="modal fade" id="modalDelete">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Xoá danh mục</h4>
			</div>
			<div class="modal-body">
				Bạn có muốn xoá danh mục này?
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
				<button type="button" class="btn btn-danger btnConfirm">Xoá</button>
			</div>
		</div>
	</div>
</div>

<script>
	var url = "<?= $this->url('question')?>" + "/category";
</script>

<?= $this->inlineScript()->setFile($this->basePath('/js/app/category.js'))?>

<?php endif; ?>
</div>