<div class="container">
<?php if(isset($error)): ?>
<div class="panel panel-danger">
	<div class="panel-heading">
		<h3 class="panel-title">Thông báo</h3>
	</div>
	<div class="panel-body">
		<?= $error ?>
	</div>
</div>

<?php else: ?>

<?= $this->inlineScript()->setFile($this->basePath('js/mustache.min.js'))?>
<?= $this->inlineScript()->setFile($this->basePath('js/jquery.multi-select.js'))?>
<?= $this->inlineScript()->setFile($this->basePath('js/jQuery.tagify.min.js'))?>
<?= $this->inlineScript()->setFile($this->basePath('js/google-chart-loader.js'))?>

<?=  $this->headTitle('Bộ câu hỏi')?>
<div class="panel panel-default">
	<div class="panel-heading">
		<h5 class="panel-title">Tìm kiếm câu hỏi</h5>
	</div>
	<div class="panel-body">
		<form class="form-inline">
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-bars" aria-hidden="true"></i> Nội dung</div>
				<input type="text" class="form-control" name="search_text" placeholder="Nhập nội dung câu hỏi cần tìm"/>
			</div>
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-check" aria-hidden="true"></i> Loại câu</div>
				<select name="filter_question_type" class="form-control">
				</select>
			</div>

			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-tag" aria-hidden="true"></i> Danh mục</div>
				<select name="filter_category" class="form-control">
				</select>
			</div>

			<?php
				if(isset($admin))
				{
					echo "<script>var admin = true; </script>";
					echo "<input type='hidden' name='admin_user_id' value='$admin->user_id' />";

					$arr = [];
					foreach ($users as $item) {
						$arr[] = $item;
					}
				}

				if(isset($admin) && !isset($test_id)):
			?>
			<div class="input-group">
				<div class="input-group-addon"><i class="fa fa-user" aria-hidden="true"></i> Người tạo câu hỏi</div>
				<select name="filter_user" class="form-control" >
					<?php

						foreach ($arr as $item) {
							echo "<option value='{$item['user_id']}'>{$item['username']}</option>";
						}
					?>
					<option value='0' selected>Tất cả</option>
				</select>
			</div>
			<?php endif;?>

			<?php
				if(isset($admin))
				{
					$sel = "<div class='input-group'><div class='input-group-addon'><i class='fa fa-user' aria-hidden='true'></i> Người tạo câu hỏi</div><select name='users' class='form-control'>";
					$sel .="<option value='' selected>Chọn tài khoản</option>";
					
					foreach ($arr as $item) {
						$sel .="<option value='{$item['user_id']}'>{$item['username']}</option>";
					}
					
					$sel .="</select></div></div>";
					echo '<script>var users = "'.$sel.'";</script>';
				}
			?>

			<div class="input-group">
				<div class="input-group-addon"><span class="glyphicon glyphicon-screenshot" aria-hidden="true"></span> Đến câu thứ:</div>
				<input name="index_question" type="number" class="form-control" style="width: 70px">
			</div>

		</form>
	</div>
</div>

<div class="panel panel-info">
	<div class="panel-heading panel-button">
		<div class="dropdown pull-right" id="menuAdd">

			<button type="button" class="btn btn-default btn-sm dropdown-toggle" data-toggle="dropdown" style="color: #555555"><i class="fa fa-plus" aria-hidden="true"></i> Thêm câu hỏi <span class="caret"></span></button>
			
			<ul class="dropdown-menu">
				<li><a href="#addNew"><i class="fa fa-file-o" aria-hidden="true"></i>
 Tạo mới</a></li>
 				<li class="divider"></li>
				<?php 
					if(isset($test_id))
						echo '<li><a href="#modalAddQuestion" data-toggle="modal"> <i class="fa fa-university" aria-hidden="true"></i>
Bộ câu hỏi</a></li>';
				?>
				<li><a href="#modalImportFromTest" data-toggle="modal"><i class="fa fa-external-link" aria-hidden="true"></i>
 Từ đề thi mở</a></li>
				<li><a href="#import"><i class="fa fa-upload" aria-hidden="true"></i>
 Từ tập tin</a></li>
			</ul>

			<?php
				if(isset($test_id))
					$urlExport = $this->url('question', ['action' => 'export', 'id' => $test_id]);
				else
					$urlExport = $this->url('question', ['action' => 'export']);
			?>

			<a href="<?= $urlExport?>" type="button" class="btn btn-success btn-sm"><i class="fa fa-download" aria-hidden="true"></i> Sao lưu</a>

		</div>
		<h5 class="panel-title">Danh sách câu hỏi - Tổng câu hỏi: <span class="badge number_total_question">0</span></h5>
	</div>
	<div class="panel-body" id="listQuestion">
	</div>
</div>

<div class="modal fade" id="modalAssign">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Quản lí</h4>
			</div>
			<div class="modal-body">
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modalImportFromTest">
	<div class="modal-dialog modal-lg" style="width: 90%;">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Tìm kiếm câu hỏi từ đề thi chia sẻ</h4>
			</div>
			<div class="modal-body">
				<div class="row">
					<div class="col-sm-4">
						<div class="panel panel-default" style="min-height: 150px">
							<div class="panel-heading">
								<h3 class="panel-title">Tìm kiếm đề</h3>
							</div>
							<div class="panel-body">
								<form method="post">
									<div class="input-group">
										<input type="text" class="form-control" id="search_name" placeholder="Nhập từ khoá" required>
										<span class="input-group-btn">
											<button type="submit" class="btn btn-default btnSearch">Tìm kiếm</button>
										</span>
									</div>
								</form>
								<hr/>
								<div class="listTest">
								</div>
							</div>
						</div>
					</div>
					<div class="col-sm-8">
						<div class="panel panel-info" style="min-height: 150px">
							<div class="panel-heading">
								<h3 class="panel-title title-list">Danh sách câu hỏi</h3>
							</div>
							<div class="panel-body list">
							</div>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
				<button type="button" class="btn btn-primary btnAdd">Thêm vào đề thi</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modalAddCategory">
	<div class="modal-dialog modal-sm">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Thêm danh mục mới</h4>
			</div>
			<div class="modal-body">
				<form method="post" action="">
					<div class="form-group">
						<input type="text" class="form-control" name="add_category" placeholder="Nhập tên thể loại mới" required>
					</div>
					<button type="submit" class="btn btn-primary btnAdd">Thêm</button>
				</form>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modalAddQuestion">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Chọn câu hỏi từ bộ câu hỏi</h4>
			</div>
			<div class="modal-body">
				<select name="category_import" id="category_import" class="form-control">
				</select>

				<div class="table-responsive" id="table_question_import">
					<table class="table table-hover">
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
				<button type="button" class="btn btn-primary btnAdd">Thêm vào đề</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modalStatistical">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Thống kê</h4>
			</div>
			<div class="modal-body">
				<div id="pie-chart"></div>
				<div id="bar-chart"></div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
			</div>
		</div>
	</div>
</div>

<div class="modal fade" id="modalDelete">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title">Xoá câu hỏi</h4>
			</div>
			<div class="modal-body">
				Bạn có muốn xoá câu hỏi này?
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default" data-dismiss="modal">Đóng</button>
				<button type="button" class="btn btn-danger btnConfirm">Xoá</button>
			</div>
		</div>
	</div>
</div>

<script id="tmplQuestion" type="x-tmpl-mustache">

<div class="col-sm-12 div-question">
	<div class="panel panel-default panel-border-top">
		<div class="panel-body" id="q{{index}}" {{#question_id}}data-question-id="{{question_id}}"{{/question_id}}>
			<div class="row">
				<div class="col-sm-4">
					<h4><strong>Câu {{ index }} {{#question_id}}(QID: {{question_id}}){{/question_id}} </strong></h4>
				</div>

				<div class="col-sm-8 text-right">
					<div id="btn-group-{{index}}" style="margin: 5px 0">
						<a href="#" class="btnStatistical"><i class="fa fa-pie-chart" aria-hidden="true"></i>
			 Thống kê</a>
						<a href="#" class="btnCopy"><i class="fa fa-clone" aria-hidden="true"></i> Sao chép câu hỏi</a>
						<a href="#" class="btnEdit"><i class="fa fa-pencil-square-o" aria-hidden="true"></i>
			 Sửa câu hỏi</a>
						<a href="#modalAssign" data-toggle="modal" class="btnAssign"><i class="fa fa-link" aria-hidden="true"></i>
			 Quản lý</a>
						<a href="#" class="btnDelete"><i class="fa fa-trash" aria-hidden="true"></i>
			 Xoá câu hỏi</a>
					</div>
				</div>
			</div>

			<div class="panel panel-question-text">
				<div class="panel-body">
					{{ &question_text }}
				</div>
			</div>

			<div>Danh mục: <label class="label label-primary">{{category_name}}</label> Loại câu: <label class="label label-primary">{{question_type_name}}</label></div>

			<button type="button" class="btn btn-default btn-sm btnDetail" data-toggle="collapse" data-target="#table-option-{{question_id}}" style="margin: 10px 0">Xem chi tiết</button>

			<div class="collapse" id="table-option-{{question_id}}">

				<div class="panel panel-default div-setting">
					<div class="panel-body">
						{{&toSettingHtml}}
					</div>
				</div>

				<table class="table table-option" style="margin-bottom: 0">
					<tbody>
					</tbody>
				</table>
			</div>
		</div>
	</div>
</div>
		
</script>

<script id="tmplOption1" type="x-tmpl-mustache">
	{{#question_options}}
	<tr>
		{{#is_correct}}
		<td class="index"><i class='fa fa-check text-success' aria-hidden='true'></i> {{index}}. </td>
		<td>{{ &option_text }}</td>
		{{/is_correct}}
		{{^is_correct}}
		<td class="index"><span style='padding-left: 20px'> {{index}}. </span></td>
		<td>{{ &option_text }}</td>
		{{/is_correct}}
	</tr>
	{{/question_options}}
</script>

<script id="tmplOption3" type="x-tmpl-mustache">
	{{#question_options}}
	<tr>
		<td class="index"><i class="fa fa-sort fa-2x" aria-hidden="true"></i></td>
		<td>{{ &option_text }}</td>
	</tr>
	{{/question_options}}
</script>

<script id="tmplOption4" type="x-tmpl-mustache">
	{{#question_options}}
	<tr class="row">
		<td class="col-sm-5"><div class="source">{{ &source.data }}</div></td>
		<td class="col-sm-1 text-center"><i class="fa fa-long-arrow-right fa-2x"></i></td>
		<td class="col-sm-5"><div class="target">{{ &target.data }}</div></td>
	</tr>
	{{/question_options}}
</script>

<script id="tmplOption5" type="x-tmpl-mustache">
	{{#question_options}}
	<tr class="row">
		<td class="col-sm-2"><h3 style="margin:0"><span class="label label-primary">Nhóm {{ group_text }}</span></h3></td>
		<td><input class="group_items" value="{{ group_items }}"></td>
	</tr>
	{{/question_options}}
</script>

<script id="tmplOption6" type="x-tmpl-mustache">
	{{#question_options}}
	<tr>
		<td class="index"><span style='padding-left: 20px'> - </span></td>
		<td class="option-text">{{ option_text }}</td>
	</tr>
	{{/question_options}}
</script>

<script id="tmplOption8" type="x-tmpl-mustache">
	{{#question_options}}
	<tr>
		<td class="index"><span style='padding-left: 20px'> {{index}}. </span></td>
		<td class="option-text">{{ &option_text }}</td>
	</tr>
	{{/question_options}}
</script>

<script id="tmplEdit" type="x-tmpl-mustache">
<form method="post" class="form-inline">
	<div class="input-group">
		<div class="input-group-addon">Loại câu</div>
		<select name="question_type" class="form-control" required="required">
		</select>
	</div>

	<div class="input-group">
		<div class="input-group-addon">Danh mục</div>
		<select name="category" class="form-control" required="required">
		</select>
	</div>

	<div class="input-group">
		<span class="input-group-btn">
			<button type="button" class="btn btn-default" data-target="#modalAddCategory" data-toggle="modal">Thêm danh mục</button>
		</span>
	</div>
</form>

	<h4><strong>Câu {{ index }}</strong></h4>

	<textarea id="question_text" class="form-control" rows="2" placeholder="Nhập nội dung câu hỏi">{{ question_text }}</textarea>

	<div class="panel panel-default" style="margin-top: 10px">
		<div class="panel-heading">Cài đặt thêm</div>
		<form class="form-horizontal" id="form-setting">
		</form>
	</div>

	<div class="div-option-edit">
		<button type="button" class="btn btn-default btn-sm" id="btnAddOption" style="margin: 10px 0">Thêm</button>
		<table style="width:100%" class="table-option-edit">
			<tbody>
			</tbody>
		</table>
	</div>

	<div class="btn-group">
		<button type="button" class="btn btn-success btn-sm" id="btnSaveQuestion">Lưu câu hỏi</button>
		<button type="button" class="btn btn-default btn-sm" id="btnClose">Huỷ</button>
	</div>

</script>

<script id="tmplEditOption1" type="x-tmpl-mustache">
{{#question_options}}
	<tr data-id="{{index}}">
		<td class="text-center"><i class="fa fa-sort fa-2x" aria-hidden="true"></i> <input type="radio" name="radio{{question_id}}"/></td>
		<td><textarea class="form-control option-text" placeholder="Nhập đáp án">{{ option_text }}</textarea></td>
		<td style="padding-left: 5px"><button type="button" class="btn btn-danger btn-xs btnDeleteOption">Xoá</button></td>
	</tr>
{{/question_options}}
</script>

<script id="tmplEditOption2" type="x-tmpl-mustache">
{{#question_options}}
	<tr data-id="{{index}}">
		<td class="text-center"><i class="fa fa-sort fa-2x" aria-hidden="true"></i> <input type="checkbox" {{#is_correct}}checked{{/is_correct}}/></td>
		<td><textarea class="form-control option-text" placeholder="Nhập đáp án">{{ option_text }}</textarea></td>
		<td style="padding-left: 5px"><button type="button" class="btn btn-danger btn-xs btnDeleteOption">Xoá</button></td>
	</tr>
{{/question_options}}
</script>

<script id="tmplEditOption3" type="x-tmpl-mustache">
{{#question_options}}
	<tr data-id="{{index}}">
		<td class="text-center"><i class="fa fa-sort fa-2x" aria-hidden="true"></i></td>
		<td><textarea class="form-control option-text" placeholder="Nhập đáp án">{{ option_text }}</textarea></td>
		<td style="padding-left: 5px"><button type="button" class="btn btn-danger btn-xs btnDeleteOption">Xoá</button></td>
	</tr>
{{/question_options}}
</script>

<script id="tmplEditOption4" type="x-tmpl-mustache">
{{#question_options}}
	<tr data-id="{{index}}" class="row">
		<td class="col-sm-5"><textarea class="source">{{&source.data}}</textarea></td>
		<td><td class="col-sm-1 text-center"><i class="fa fa-long-arrow-right fa-2x"></i></td></td>
		<td class="col-sm-5"><textarea class="target">{{&target.data}}</textarea></td>
		<td class="col-sm-1"><button type="button" class="btn btn-danger btn-xs btnDeleteOption">Xoá</button></td>
	</tr>
{{/question_options}}
</script>

<script id="tmplEditOption5" type="x-tmpl-mustache">
{{#question_options}}
	<tr data-id="{{index}}">
		<td>Tên nhóm: 
			<input class="form-control group-text" placeholder="Nhập tên nhóm" value="{{group_text}}"><br/>
			Các thành phần:
			<input class="group-items" placeholder="Nhập tên các thành phần" value="{{group_items}}">
		</td>
		<td style="padding-left: 5px"><button type="button" class="btn btn-danger btn-xs btnDeleteOption">Xoá</button></td>
	</tr>
{{/question_options}}
</script>

<script id="tmplEditOption6" type="x-tmpl-mustache">
{{#question_options}}
	<tr data-id="{{index}}">
		<td class="text-center">-</i>
		<td><input class="form-control option-text" placeholder="Nhập đáp án" value="{{ option_text }}"/></td>
		<td style="padding-left: 5px"><button type="button" class="btn btn-danger btn-xs btnDeleteOption">Xoá</button></td>
	</tr>
{{/question_options}}
</script>

<script id="tmplEditOption8" type="x-tmpl-mustache">
{{#question_options}}
	<tr data-id="{{index}}">
		<td><textarea class="form-control option-text" placeholder="Nhập đáp án">{{ option_text }}</textarea></td>
		<td style="padding-left: 5px"><button type="button" class="btn btn-danger btn-xs btnDeleteOption">Xoá</button></td>
	</tr>
{{/question_options}}
</script>

<script id="tmplEditSetting1" type="x-tmpl-mustache">
<div class="form-group form-group-sm">
	<label class="col-sm-2 control-label">Điểm số: </label>
	<div class="col-sm-2">
		<input class="form-control" id="point" type="number" min="0.1" step="0.1" value="{{#getSetting}}point{{/getSetting}}" required>
	</div>
</div>
<div class="form-group form-group-sm">
	<label class="col-sm-2 control-label">Phản hồi: </label>
	<div class="col-sm-9">
		<textarea class="form-control" id="feedback">{{#getSetting}}feedback{{/getSetting}}</textarea>
	</div>
</div>
</script>

<script id="tmplEditSetting8" type="x-tmpl-mustache">
<div class="form-group form-group-sm">
	<label class="col-sm-2 control-label">Số từ: </label>
	<div class="col-sm-2">
		<input class="form-control" id="word-count" type="number" min="1" step="1" value="{{#getSetting}}word_count{{/getSetting}}" required>
	</div>
</div>
</script>

<script id="tmplEditSetting9" type="x-tmpl-mustache">
<div class="form-group form-group-sm">
	<label class="col-sm-2 control-label">Loại tệp: </label>
	<div class="col-sm-2">
		<input class="form-control" id="file-type" value="{{#getSetting}}file_type{{/getSetting}}" required>
	</div>
</div>
<div class="form-group form-group-sm">
	<label class="col-sm-2 control-label">Kích thước (Max: 25MB): </label>
	<div class="col-sm-2">
		<div class="input-group">
			<input class="form-control" max="89" id="file-size" type="number" min="0.1" max="25" step="0.1" value="{{#getSetting}}file_size{{/getSetting}}" required>
			<span class="input-group-addon">MB</span>
		</div>
	</div>
</div>
<div class="form-group form-group-sm">
	<label class="col-sm-2 control-label">Số lượng file: </label>
	<div class="col-sm-2">
		<input class="form-control" id="file-count" value="{{#getSetting}}file_count{{/getSetting}}" required>
	</div>
</div>
</script>

<style>
	#form-setting{
		margin: 10px 0;
	}
</style>

<script type="text/javascript">
	var urlQuestion = "<?= $this->url('question', [], ['force_canonical' => true] ) ?>";
	var urlTest = "<?= $this->url('test', [],['force_canonical' => true]) ?>";
</script>

<?= $this->inlineScript()->setFile($this->basePath('/js/app/question.js')) ?>

<?php endif; ?>
</div>